### ISSUE TITLE
Locks folders (cannot rename/delete) on Windows

### ISSUE THREAD

**Issue by andreialecu** [atom/node-pathwatcher#101]
I believe this module may cause the problems in:
https://github.com/atom/atom/issues/3365

It appears that libuv has fixed this a while ago:
https://github.com/nodejs/node/issues/375

I think this means that recursive `fs.watch` that does not lock any folder should now be available in node core.

Can this module be fixed? Alternatively, could it be replaced with something like chokidar instead? 

What does this module do that others don't?

**Comment by kumarharsh** [comment]
I get this error while deleting:

```
Error: EBUSY: resource busy or locked, rmdir 'D:\src\app\shared\components\<MyFolder>'
    at Error (native)
```

**Comment by hartalex** [comment]
It appears that the call to ReadDirectoryChangesW is locking the monitored directory.  This is a quirk of Windows.  PathWatcher.watch isn't recursive, each directory that is monitored will be locked.  I think a solution would be to implement a recursive version of PathWatcher.watch.  This way only the top level directory will be locked and all of the sub directories will no longer be locked.

**Comment by rsese** [comment]
@andreialecu - we have a new file watcher system that's not enabled by default but is available at `Settings > File System Watcher` if you set it to `Experimental filesystem watching library`. Can you give this setting a try on the latest versions of Atom, and let us know if you still the same behavior?

**Comment by rsese** [comment]
ahh sorry - was just chatting with another maintainer and see that using the new file watcher setting won't help with https://github.com/atom/atom/issues/3365 because the tree view would also need to be updated to use the new file watcher system.

Since the team will use https://github.com/atom/atom/issues/3365 to track the issue, we're going to go ahead and close this in favor of https://github.com/atom/atom/issues/3365.
